### ISSUE TITLE
Possible fogger to request to send code to this phone as it was in fast lane

### ISSUE THREAD

**Issue by rctphone** [fb929/pyappstoreconnect#1]
https://github.com/fb929/pyappstoreconnect/blob/a11fc948285afbf397880f478e304446ba150dba/pyappstoreconnect/client.py#L229

This code should be there, otherwise no code has sent

```python
payload = {
            "phoneNumber": {
                "id": phoneId,
            },
            "mode": pushMode,
        }
        headers = self.appleSessionHeaders()
        r = self.session.put(f"https://idmsa.apple.com/appleauth/auth/verify/{codeType}", json=payload,
                              headers=headers)
        self.logger.debug(f"{defName}: response.status_code={r.status_code}")
        self.logger.debug(f"{defName}: response.json()={json.dumps(r.json())}")
        if r.status_code != 200:
            return False
```

**Comment by fb929** [comment]
but it's works, the code is sent on this step:
https://github.com/fb929/pyappstoreconnect/blob/a11fc948285afbf397880f478e304446ba150dba/pyappstoreconnect/client.py#L181

maybe, you mean situation, where we have more than one phone number ?
